package ch.admin.foitt.wallet.platform.genericScreens.domain.model

enum class GenericErrorScreenState {
    GENERIC,
    INVALID_REQUEST,
    INVALID_REQUEST_BEARER_TOKEN,
    INVALID_GRANT,
    INVALID_CLIENT,
    INVALID_CREDENTIAL_REQUEST,
    UNKNOWN_CREDENTIAL_CONFIGURATION,
    UNKNOWN_CREDENTIAL_IDENTIFIER,
    INVALID_PROOF,
    INVALID_NONCE,
    INVALID_ENCRYPTION_PARAMETERS,
    CREDENTIAL_REQUEST_DENIED,
    INVALID_TRANSACTION_ID,
    INSUFFICIENT_SCOPE,
    INVALID_TOKEN,
    UNAUTHORIZED_CLIENT,
    UNAUTHORIZED_GRANT_TYPE
}
